name: Playwright Tests and GitHub Pages Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run Playwright Tests
      run: npm test
      continue-on-error: true  # Allows the workflow to continue even if tests fail

    - name: Upload Pages Artifact
      uses: actions/upload-artifact@v4  # Ensure correct version is used
      with:
        name: github-pages  # Must match expected artifact name
        path: playwright-report/  # Directory where Playwright report is generated

    - name: Configure Pages
      uses: actions/configure-pages@v4

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
