name: PHP CI with MariaDB

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # This sets the timeout for the entire job to 1 minute
    env:
      PLAYWRIGHT_IMAGE: mcr.microsoft.com/playwright:v1.42.1-jammy

    services:
      playwright:
        image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
    - uses: actions/checkout@v4

    - name: Show PHP Version
      run: php -v

    - name: Show PHP Composer Version
      run: composer -v

    - name: Copy Config File
      run: cp config.ini.CI config.ini

    - name: Utilities Test
      run: php ./unittest/utilities.php

    - name: Setup E2E Tests
      run:  bash ./e2e/setup-e2e-tests.sh

    - name: Install dependencies
      run: docker run --rm --network="host" -v $(pwd):/repo -w /repo/e2e ${{ env.PLAYWRIGHT_IMAGE }} npm ci

    - name: Show Playwright version
      run: docker run --rm --network="host" -v $(pwd):/repo -w /repo/e2e ${{ env.PLAYWRIGHT_IMAGE }} npx playwright --version

    - name: List contents of e2e directory before tests
      run: tree -I node_modules
      working-directory: e2e
      if: always()

    - name: Run Playwright Tests
      run: docker run --rm --network="host" -e CI=true -v $(pwd):/repo -w /repo ${{ env.PLAYWRIGHT_IMAGE }} npx playwright test

    - name: List contents of e2e directory after tests
      run: tree -I node_modules
      working-directory: e2e
      if: always()
      
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-artifacts
        path: |
          e2e/playwright-report/
          e2e/test-results/
          e2e/php_server*.log
        retention-days: 3
