name: Playwright Tests and GitHub Pages Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        id: playwright-tests
        run: npm test

      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Test Report to GitHub Pages
        if: ${{ always() }}
        uses: actions/deploy-pages@v4

      - name: Display Deployment URL
        if: ${{ always() }}
        run: |
          echo "Your test report is live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
