name: Playwright Tests and GitHub Pages Deployment

on:
  push:
    branches: [main, feature-*]  # Include any branches you want to deploy
  pull_request:
    branches: [main, feature-*]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}  # Use the branch name as the environment
      url: https://${{ github.repository_owner }}--${{ github.ref_name }}.github.io/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm test
        continue-on-error: true

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/  # Upload the current branch's report
          retention-days: 7  # Ensure old artifacts are removed after 7 days

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
