name: Playwright and PHP Unit Tests Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust this to match your project's PHP version
          extensions: mbstring, pdo, pgsql, pdo_pgsql, json
          tools: composer

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..60}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres
            if [ $? -eq 0 ]; then
              echo "PostgreSQL is ready"
              break
            else
              echo "Waiting for PostgreSQL..."
              sleep 2
            fi
          done

      - name: Check PostgreSQL Status (Debug)
        run: |
          echo "Checking PostgreSQL status..."
          pg_isready -h 127.0.0.1 -p 5432 -U postgres
          if [ $? -eq 0 ]; then
            echo "PostgreSQL is up and accepting connections."
          else
            echo "PostgreSQL is not accepting connections. Exiting."
            exit 1
          fi

      - name: Check Open Ports (Debug)
        run: |
          echo "Checking open ports..."
          netstat -an | grep 5432 || echo "Port 5432 is not open."

      - name: List Running Processes (Debug)
        run: |
          echo "Listing PostgreSQL processes..."
          ps aux | grep postgres

      - name: Setup Database and User
        run: |
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -c "CREATE USER yasu WITH PASSWORD 'tng123';"
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -c "ALTER USER yasu CREATEDB;"
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE tng OWNER yasu;"
        env:
          PGPASSWORD: postgres

      - name: Test Database Connection
        run: |
          PGPASSWORD='tng123' psql -h 127.0.0.1 -p 5432 -U yasu -d tng -c '\q'
        env:
          PGPASSWORD: tng123

      - name: Apply Database Schema
        run: |
          PGPASSWORD='tng123' psql -h 127.0.0.1 -U yasu -d tng -f opendata_schema.sql
        env:
          PGPASSWORD: tng123

      - name: Copy app-yasu.json to app.json
        run: cp app-yasu.json app.json

      - name: Update Port in app.json
        run: |
          sed -i 's/"port": "5532"/"port": "5432"/' app.json

      - name: Install PHP Dependencies (Vendor Directory)
        run: |
          cd app
          composer install

      - name: Run PHP Unit Tests
        run: |
          ./app/vendor/bin/phpunit --configuration phpunit.xml 

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        id: playwright-tests
        run: npm test

      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

  deploy-report:
    needs: run-tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Test Report to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Display Deployment URL
        run: |
          echo "Your test report is live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
